@echo off
set ROOT=d:\CRW
@set SRC_DB=depot:d:\CRW\CRWM.GDB
@set SRC_PSW="byntuhfnjh"
@set IB_CLIENT="C:\FB25\bin\fbclient.dll"
@set META_FILENAME=d:\CRW\export\CRW_META.SQL
@set DATA_TABLES="DUMMY, ENTC_CMD, ENTC_GRP, ENTC_UI, ENTC_UICLASS, ENT_ENTITIES, ENT_FIELDS, ENT_OPERS, ENT_VIEWS, ENT_VIEW_LINKS, INF_DICT, INF_ENUM, SEC_ACL, SEC_PERMISSIONS, SEC_POLICIES, SEC_USERS, SEC_USER_ROLES"

